'use client'
import { useEffect, type FC } from 'react'
import { Heading, Text } from '@chakra-ui/react'
import { useDashboard, useTickets } from '@/hooks'
import { SiteConfig } from '@/lib'
import {
  DashboardSectionItem,
  DashboardSectionLoading,
  DashboardSectionTitle
} from '@/components/dashboard'

export const DashboardTicketPage: FC<{ ticketId: string }> = ({ ticketId }) => {
  const {
    state: { ticket },
    dispatch
  } = useDashboard()
  const { fetchTicket, resolveTicket, resolveTicketLoading } = useTickets()

  useEffect(() => {
    fetchTicket(ticketId)

    return () =>
      dispatch({
        type: 'SET_TICKET',
        payload: undefined
      })
  }, [])

  useEffect(() => {
    if (ticket) {
      window.document.title = `${ticket.referenceId} - ${SiteConfig.baseTitle}`
    }
  }, [ticket])

  if (!ticket) return <DashboardSectionLoading primaryButton secondaryButton />

  return (
    <>
      <DashboardSectionTitle
        primaryButton={{
          children: 'Mark As Resolved',
          isLoading: resolveTicketLoading,
          onClick: () => resolveTicket(ticket._id)
        }}
        back={{
          path: '/dashboard/tickets',
          children: 'Tickets'
        }}
      >
        {ticket.referenceId}
      </DashboardSectionTitle>
      <DashboardSectionItem title='Reference ID'>
        <Heading fontSize='1.5em' color='secondary.900'>
          {ticket.referenceId}
        </Heading>
      </DashboardSectionItem>
      <DashboardSectionItem title='Customer Name'>
        <Heading fontSize='1.5em' color='secondary.900'>
          {ticket.name || 'N/A'}
        </Heading>
      </DashboardSectionItem>
      <DashboardSectionItem title='Customer Email'>
        <Heading fontSize='1.5em' color='secondary.900'>
          {ticket.email}
        </Heading>
      </DashboardSectionItem>
      <DashboardSectionItem title='Details (generated by A.I. on behalf of the customer)'>
        <Heading fontSize='1.5em' color='secondary.900'>
          {ticket.details}
        </Heading>
      </DashboardSectionItem>
    </>
  )
}
